/**
 * The way back from E3.
 *
 * Undoing a migration is where data gets destroyed, because "revert" is usually
 * read as "delete everything the migration touched" — and the migration touched
 * the collection that also holds the only record of what real sessions had
 * prescribed. So this draws a line that has nothing to do with which collection a
 * row is in:
 *
 *   derived → may go        (seeded baseline, migrated adjustments, reconstructions)
 *   observed → stays        (committed snapshots, adjustments you wrote)
 *
 * A committed snapshot is never removed by a rollback. It is not a migration
 * artifact: it is what a session had in front of it that day, and no amount of
 * going back makes that untrue. Same for an adjustment you authored — deleting a
 * decision in order to be able to revert would be the sin E3 exists to prevent.
 */

import type {
	PlanAdjustment,
	PrescriptionBaseline,
	SessionPlanSnapshot,
	SessionRecord,
} from "@/domain/schema";

export type RollbackPlan = {
	/** Seeded from content; regenerated by re-running the migration. */
	removeBaselineIds: string[];
	/** `provenance.kind === "migrated"`. Everything authored stays. */
	removeAdjustmentIds: string[];
	/** Reconstructions only. A deduction can be deduced again. */
	removeSnapshotIds: string[];
	/** Sessions the migration marked `legacy`, back to stating nothing. */
	clearContractSessionIds: string[];
	/** What is deliberately being left behind, so the report can say so. */
	kept: {
		authoredAdjustmentIds: string[];
		committedSnapshotIds: string[];
		snapshotContractSessionIds: string[];
	};
};

export function planRollback(input: {
	baseline: readonly PrescriptionBaseline[];
	adjustments: readonly PlanAdjustment[];
	snapshots: readonly SessionPlanSnapshot[];
	sessions: readonly SessionRecord[];
}): RollbackPlan {
	const migrated = (adjustment: PlanAdjustment) =>
		adjustment.provenance.kind === "migrated";

	return {
		removeBaselineIds: input.baseline.map((row) => row.id),
		removeAdjustmentIds: input.adjustments
			.filter(migrated)
			.map((adjustment) => adjustment.id),
		removeSnapshotIds: input.snapshots
			.filter((snapshot) => snapshot.status === "reconstructed")
			.map((snapshot) => snapshot.id),
		clearContractSessionIds: input.sessions
			.filter((session) => session.prescriptionContract === "legacy")
			.map((session) => session.id),
		kept: {
			authoredAdjustmentIds: input.adjustments
				.filter((adjustment) => !migrated(adjustment))
				.map((adjustment) => adjustment.id),
			committedSnapshotIds: input.snapshots
				.filter((snapshot) => snapshot.status === "committed")
				.map((snapshot) => snapshot.id),
			// A session created under E3 keeps saying so. Clearing it would turn a
			// real snapshot_v1 session into one that looks pre-E3, and recovery would
			// then reconstruct over the top of a snapshot that was never lost.
			snapshotContractSessionIds: input.sessions
				.filter((session) => session.prescriptionContract === "snapshot_v1")
				.map((session) => session.id),
		},
	};
}

/** Applies a plan to the four record lists, returning new ones. */
export function applyRollback(
	input: {
		baseline: readonly PrescriptionBaseline[];
		adjustments: readonly PlanAdjustment[];
		snapshots: readonly SessionPlanSnapshot[];
		sessions: readonly SessionRecord[];
	},
	plan: RollbackPlan,
) {
	const gone = {
		baseline: new Set(plan.removeBaselineIds),
		adjustments: new Set(plan.removeAdjustmentIds),
		snapshots: new Set(plan.removeSnapshotIds),
	};
	const clearing = new Set(plan.clearContractSessionIds);

	return {
		baseline: input.baseline.filter((row) => !gone.baseline.has(row.id)),
		adjustments: input.adjustments.filter(
			(adjustment) => !gone.adjustments.has(adjustment.id),
		),
		snapshots: input.snapshots.filter(
			(snapshot) => !gone.snapshots.has(snapshot.id),
		),
		sessions: input.sessions.map((session) =>
			clearing.has(session.id)
				? {
						...session,
						prescriptionContract: null,
						// Only the pointer it never really had. A session whose snapshot
						// survives keeps pointing at it.
						snapshotId: gone.snapshots.has(session.snapshotId ?? "")
							? null
							: session.snapshotId,
					}
				: session,
		),
	};
}
