/**
 * Builds the service worker.
 *
 * Replaces vite-plugin-pwa, which does not emit a worker under TanStack Start's
 * two-environment build (client + server) on Vite 8 — it writes the manifest and
 * the registration shim, then silently skips Workbox.
 *
 * Writing it directly is a fair trade here, because the caching policy this app
 * needs is one rule: the whole build is precached and served cache-first, since
 * everything it does is local anyway. There is nothing for Workbox to arbitrate.
 */

import { createHash } from 'node:crypto'
import { existsSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, posix, relative, sep } from 'node:path'
import type { Plugin } from 'vite'

const PRECACHE_EXTENSIONS = /\.(js|css|html|json|webmanifest|png|svg|ico|woff2|wasm)$/

export function serviceWorker(publicDir: string): Plugin {
  return {
    name: 'tracker-service-worker',
    apply: 'build',
    writeBundle: {
      order: 'post',
      handler(options, bundle) {
        // Only the client build produces files a browser will ever fetch.
        if (this.environment?.name !== 'client') return
        const outDir = options.dir
        if (!outDir) return

        const built = Object.keys(bundle)
          .filter((file) => PRECACHE_EXTENSIONS.test(file))
          .map((file) => `/${posix.join(...file.split(sep))}`)

        const urls = [...new Set(['/', ...built, ...listPublicFiles(publicDir)])].sort()

        // The cache name changes only when the asset list changes, so a rebuild
        // that produces identical output does not evict a working cache.
        const version = createHash('sha256').update(urls.join('\n')).digest('hex').slice(0, 12)

        writeFileSync(join(outDir, 'sw.js'), renderWorker(urls, version), 'utf8')
        this.info?.(`service worker: ${urls.length} files precached (${version})`)
      },
    },
  }
}

/** Static files Vite copies verbatim; they are not part of the bundle graph. */
function listPublicFiles(publicDir: string): string[] {
  if (!existsSync(publicDir)) return []

  const walk = (dir: string): string[] =>
    readdirSync(dir).flatMap((entry) => {
      const full = join(dir, entry)
      if (statSync(full).isDirectory()) return walk(full)
      return PRECACHE_EXTENSIONS.test(entry)
        ? [`/${relative(publicDir, full).split(sep).join('/')}`]
        : []
    })

  return walk(publicDir)
}

/**
 * Exported so the tests can run the worker they will actually ship rather than
 * a paraphrase of it. What broke in T-003 was a caching rule, and a rule is only
 * worth asserting against the code that enforces it.
 */
export function renderWorker(urls: readonly string[], version: string): string {
  return `// Generated by plugins/service-worker.ts — do not edit.
const CACHE = 'operacion-tesis-${version}'
const PRECACHE = ${JSON.stringify(urls, null, 2)}

// \`Vary\` is ignored on purpose, and this is the whole of T-003.
//
// The precache is filled with \`cache.add(url)\`, whose request carries no
// \`Origin\` header. A module script is fetched in CORS mode and does carry one.
// Servers commonly answer assets with \`Vary: Origin\` — vite preview does — and
// then \`caches.match(request)\` compares the two and reports a miss for a file
// that is sitting right there. Online the miss falls through to the network and
// nobody notices; offline the route never loads.
//
// These names carry a content hash, so the URL is the whole identity: no header
// can legitimately select a different body, and honouring \`Vary\` can only turn
// a hit that had to happen into a miss.
const MATCH = { ignoreVary: true }

self.addEventListener('install', (event) => {
  // Skip waiting: there is a single user and no open tab worth preserving a
  // stale version for.
  event.waitUntil(
    caches
      .open(CACHE)
      // Individually, so one 404 cannot fail the whole install.
      .then((cache) => Promise.allSettled(PRECACHE.map((url) => cache.add(url))))
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('push', (event) => {
  // A push with an unreadable body still has to raise something: iOS revokes the
  // permission of a worker that receives one and shows nothing.
  let payload = {}
  try {
    payload = event.data ? event.data.json() : {}
  } catch (error) {
    payload = {}
  }

  event.waitUntil(
    self.registration.showNotification(payload.title || 'Operación Tesis', {
      body: payload.body || '',
      icon: '/icon-192.png',
      badge: '/icon-192.png',
      tag: payload.tag || 'reminder',
      data: { url: payload.url || '/' },
    }),
  )
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const target = new URL((event.notification.data && event.notification.data.url) || '/', self.location.origin).href

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windows) => {
      // Focus the app if it is already open rather than stacking another window.
      const open = windows.find((client) => client.url.startsWith(self.location.origin))
      if (open) return open.focus()
      return self.clients.openWindow(target)
    }),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  // Navigations go to the network first, falling back to cache when offline.
  // Cache-first here would pin the app to whatever HTML was cached the day it
  // was installed: the shell names the hashed asset files, so a stale shell
  // means a permanently stale app no matter how many times it updates.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          // Only a navigation to '/' may become the offline shell. Every route
          // returns different HTML — each one preloads its own chunks — so
          // caching whichever route you happened to visit would leave the app
          // opening offline into a shell that never mentions the entry chunk.
          if (url.pathname === '/' && response.ok && response.type === 'basic') {
            const copy = response.clone()
            caches.open(CACHE).then((cache) => cache.put('/', copy))
          }
          return response
        })
        .catch(() => caches.match('/', MATCH).then((cached) => cached ?? Response.error())),
    )
    return
  }

  // Everything else is content-hashed, so cache-first is both safe and fast.
  event.respondWith(
    caches.match(request, MATCH).then((cached) => {
      if (cached) return cached

      return fetch(request)
        .then((response) => {
          // Cache successful same-origin responses so assets fetched lazily
          // (a route chunk, the sqlite wasm) are there next time, offline.
          if (response.ok && response.type === 'basic') {
            const copy = response.clone()
            caches.open(CACHE).then((cache) => cache.put(request, copy))
          }
          return response
        })
        .catch(() => {
          // Offline and never seen: navigations fall back to the app shell so
          // the app still opens; anything else genuinely fails.
          // Navigations were handled above; a hashed asset that was never
          // cached and cannot be fetched has no sensible substitute.
          throw new Error('offline')
        })
    }),
  )
})
`
}
