/**
 * Builds the service worker.
 *
 * Replaces vite-plugin-pwa, which does not emit a worker under TanStack Start's
 * two-environment build (client + server) on Vite 8 — it writes the manifest and
 * the registration shim, then silently skips Workbox.
 *
 * Writing it directly is a fair trade here, because the caching policy this app
 * needs is one rule: the whole build is precached and served cache-first, since
 * everything it does is local anyway. There is nothing for Workbox to arbitrate.
 */

import { createHash } from 'node:crypto'
import { existsSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, posix, relative, sep } from 'node:path'
import type { Plugin } from 'vite'

const PRECACHE_EXTENSIONS = /\.(js|css|html|json|webmanifest|png|svg|ico|woff2|wasm)$/

export function serviceWorker(publicDir: string): Plugin {
  return {
    name: 'tracker-service-worker',
    apply: 'build',
    writeBundle: {
      order: 'post',
      handler(options, bundle) {
        // Only the client build produces files a browser will ever fetch.
        if (this.environment?.name !== 'client') return
        const outDir = options.dir
        if (!outDir) return

        const built = Object.keys(bundle)
          .filter((file) => PRECACHE_EXTENSIONS.test(file))
          .map((file) => `/${posix.join(...file.split(sep))}`)

        const urls = [...new Set(['/', ...built, ...listPublicFiles(publicDir)])].sort()

        // The cache name changes only when the asset list changes, so a rebuild
        // that produces identical output does not evict a working cache.
        const version = createHash('sha256').update(urls.join('\n')).digest('hex').slice(0, 12)

        writeFileSync(join(outDir, 'sw.js'), renderWorker(urls, version), 'utf8')
        this.info?.(`service worker: ${urls.length} files precached (${version})`)
      },
    },
  }
}

/** Static files Vite copies verbatim; they are not part of the bundle graph. */
function listPublicFiles(publicDir: string): string[] {
  if (!existsSync(publicDir)) return []

  const walk = (dir: string): string[] =>
    readdirSync(dir).flatMap((entry) => {
      const full = join(dir, entry)
      if (statSync(full).isDirectory()) return walk(full)
      return PRECACHE_EXTENSIONS.test(entry)
        ? [`/${relative(publicDir, full).split(sep).join('/')}`]
        : []
    })

  return walk(publicDir)
}

function renderWorker(urls: readonly string[], version: string): string {
  return `// Generated by plugins/service-worker.ts — do not edit.
const CACHE = 'operacion-tesis-${version}'
const PRECACHE = ${JSON.stringify(urls, null, 2)}

self.addEventListener('install', (event) => {
  // Skip waiting: there is a single user and no open tab worth preserving a
  // stale version for.
  event.waitUntil(
    caches
      .open(CACHE)
      // Individually, so one 404 cannot fail the whole install.
      .then((cache) => Promise.allSettled(PRECACHE.map((url) => cache.add(url))))
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached

      return fetch(request)
        .then((response) => {
          // Cache successful same-origin responses so assets fetched lazily
          // (a route chunk, the sqlite wasm) are there next time, offline.
          if (response.ok && response.type === 'basic') {
            const copy = response.clone()
            caches.open(CACHE).then((cache) => cache.put(request, copy))
          }
          return response
        })
        .catch(() => {
          // Offline and never seen: navigations fall back to the app shell so
          // the app still opens; anything else genuinely fails.
          if (request.mode === 'navigate') return caches.match('/')
          throw new Error('offline')
        })
    }),
  )
})
`
}
