/**
 * Regenerates `content.example/` from the real content, neutralised.
 *
 * The example exists so the repo builds and runs for anyone, and so the content
 * shape has a public reference. Deriving it from the real files rather than
 * hand-writing it means it cannot drift out of the schema the moment a column
 * is added — which is exactly what happened when v3 landed.
 *
 * Nothing personal survives: generic dates, no notes, no baseline readings, and
 * only the first few exercises of each session.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse, stringify } from "yaml";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (file: string) =>
	parse(readFileSync(resolve(ROOT, "content", file), "utf8"));
const write = (file: string, data: unknown) =>
	writeFileSync(
		resolve(ROOT, "content.example", file),
		`# Generic sample, regenerated by scripts/make-example.ts.\n` +
			`# The real content lives in content/, which is gitignored — it is personal\n` +
			`# planning. This exists so the repo builds and runs for anyone.\n` +
			stringify(data, { lineWidth: 100 }),
		"utf8",
	);

const program = read("program.yaml");

write("program.yaml", {
	meta: {
		title: "Programa de ejemplo",
		startDate: "2026-01-05",
		checkpointDate: "2026-05-15",
		startWeightKg: null,
	},
	phases: program.phases.map((phase: Record<string, unknown>, index: number) => ({
		...phase,
		startDate: `2026-0${index + 1}-05`,
		endDate: index === 3 ? null : `2026-0${index + 2}-01`,
	})),
	weekStructure: program.weekStructure,
	sessions: program.sessions.map((session: Record<string, unknown>) => ({
		...session,
		exercises: (session.exercises as unknown[]).slice(0, 4),
	})),
	cardio: program.cardio,
	ankleRehab: program.ankleRehab.slice(0, 3),
	objectives: program.objectives,
	keyRules: program.keyRules,
	progressionRules: program.progressionRules,
});

write("ankle-protocol.yaml", {
	baselineDate: "2026-01-04",
	// Baseline readings are measurements of a person; the shape is what matters.
	baseline: [],
	protocol: program.ankleRehab.slice(0, 3),
	safetyNotes: read("ankle-protocol.yaml").safetyNotes,
});

write("sources.yaml", read("sources.yaml"));

console.log("content.example/ regenerado desde content/");
