/**
 * Content migration: phases stop being numbered and start being named.
 *
 * `id: 1` becomes `id: adaptacion`, `startDate` becomes `plannedStart`, and each
 * phase gains the fields E2 needs — `order`, `schedulePolicy`, `legacyId`,
 * `inheritsFrom`, `retired`.
 *
 * The ids are derived from the names once, here, and then frozen in
 * `src/domain/__fixtures__/phase-ids.ts`. Deriving an id from a name is exactly
 * the mistake the exercise ids were rescued from — the difference is that this
 * happens once, under review, and after that the id never moves again no matter
 * what the name does.
 *
 * The rename is checked before anything is written: `legacyId` has to round-trip,
 * and every phase must end up with a distinct id and order. Idempotent — a
 * program already migrated is left alone.
 *
 * Run with: npx tsx scripts/migrate-phases.ts [--check]
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse, stringify } from "yaml";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK_ONLY = process.argv.includes("--check");

/** Accent-free, lowercase, underscores. Same normalisation the exercises use. */
function slugify(name: string): string {
	return name
		.normalize("NFD")
		.replace(/[̀-ͯ]/g, "")
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "_")
		.replace(/^_+|_+$/g, "");
}

type LegacyPhase = {
	id: number;
	name: string;
	startDate: string;
	endDate: string | null;
	[key: string]: unknown;
};

const programPath = resolve(ROOT, "content", "program.yaml");
const program = parse(readFileSync(programPath, "utf8"));

const phases = program.phases as LegacyPhase[];

if (typeof phases[0]?.id === "string") {
	console.log("content/program.yaml ya tiene fases con id de texto; nada que hacer.");
	process.exit(0);
}

const migrated = phases.map((phase, index) => {
	const { id, name, startDate, endDate, ...rest } = phase;
	return {
		id: slugify(name),
		name,
		order: index + 1,
		plannedStart: startDate ?? null,
		plannedEnd: endDate ?? null,
		// Every existing phase moves with the training: none of them answers to a
		// date from outside.
		schedulePolicy: "rolling",
		entryCriteria: [],
		exitCriteria: [],
		legacyId: id,
		inheritsFrom: null,
		retired: false,
		...rest,
	};
});

// ------------------------------------------------------------------ checks

const problems: string[] = [];

const ids = migrated.map((phase) => phase.id);
if (new Set(ids).size !== ids.length) {
	problems.push(`Ids repetidos: ${ids.join(", ")}`);
}
for (const id of ids) {
	if (!/^[a-z][a-z0-9_]*$/.test(id)) problems.push(`Id inválido: "${id}"`);
}

const legacyIds = migrated.map((phase) => phase.legacyId);
if (new Set(legacyIds).size !== legacyIds.length) {
	problems.push(`legacyId repetido: ${legacyIds.join(", ")}`);
}

// The migration of stored sessions maps a number to the phase carrying it, so the
// mapping has to be total over what the sessions can hold.
for (const legacyId of [1, 2, 3, 4]) {
	if (!legacyIds.includes(legacyId)) {
		problems.push(`Ninguna fase reclama legacyId ${legacyId}`);
	}
}

console.log(`Fases: ${migrated.length}\n`);
for (const phase of migrated) {
	console.log(
		`  ${String(phase.legacyId).padEnd(2)} -> ${phase.id.padEnd(18)} ` +
			`orden ${phase.order}  ${phase.plannedStart ?? "—"} … ${phase.plannedEnd ?? "abierta"}`,
	);
}

if (problems.length > 0) {
	console.error(`\nABORTA:\n  ${problems.join("\n  ")}`);
	process.exit(1);
}

if (CHECK_ONLY) {
	console.log("\n--check: no se escribió nada.");
	process.exit(0);
}

// Cardio prescriptions are keyed by phase too, and travel with the rename.
const cardio = (program.cardio ?? []) as Array<{ phase: number }>;
const byLegacy = new Map(migrated.map((phase) => [phase.legacyId, phase.id]));
const migratedCardio = cardio.map((entry) => ({
	...entry,
	phase: byLegacy.get(entry.phase) ?? entry.phase,
}));

writeFileSync(`${programPath}.phases.bak`, readFileSync(programPath, "utf8"), "utf8");
writeFileSync(
	programPath,
	"# Generated by scripts/import-excel.ts — edit freely, it is not regenerated automatically.\n" +
		"# Los ejercicios referencian content/library.yaml; aquí vive sólo la prescripción.\n" +
		stringify(
			{ ...program, phases: migrated, cardio: migratedCardio },
			{ lineWidth: 100 },
		),
	"utf8",
);

console.log("\ncontent/program.yaml migrado (copia previa en program.yaml.phases.bak)");
console.log(`Ids: ${ids.join(", ")}`);
console.log("Congélalos en src/domain/__fixtures__/phase-ids.ts");
