/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnkleRouteImport } from './routes/ankle'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as InspoRouteImport } from './routes/inspo'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProgressRouteImport } from './routes/progress'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnkleRoute = AnkleRouteImport.update({
  id: '/ankle',
  path: '/ankle',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InspoRoute = InspoRouteImport.update({
  id: '/inspo',
  path: '/inspo',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ankle': typeof AnkleRoute
  '/history': typeof HistoryRoute
  '/inspo': typeof InspoRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ankle': typeof AnkleRoute
  '/history': typeof HistoryRoute
  '/inspo': typeof InspoRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ankle': typeof AnkleRoute
  '/history': typeof HistoryRoute
  '/inspo': typeof InspoRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ankle' | '/history' | '/inspo' | '/plan' | '/progress'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ankle' | '/history' | '/inspo' | '/plan' | '/progress'
  id:
    '__root__' | '/' | '/ankle' | '/history' | '/inspo' | '/plan' | '/progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnkleRoute: typeof AnkleRoute
  HistoryRoute: typeof HistoryRoute
  InspoRoute: typeof InspoRoute
  PlanRoute: typeof PlanRoute
  ProgressRoute: typeof ProgressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ankle': {
      id: '/ankle'
      path: '/ankle'
      fullPath: '/ankle'
      preLoaderRoute: typeof AnkleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspo': {
      id: '/inspo'
      path: '/inspo'
      fullPath: '/inspo'
      preLoaderRoute: typeof InspoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnkleRoute: AnkleRoute,
  HistoryRoute: HistoryRoute,
  InspoRoute: InspoRoute,
  PlanRoute: PlanRoute,
  ProgressRoute: ProgressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
